.TH HFS 1 "28 JUN 2012"
.SH NAME
http-file-share \- quickly share your files across the internet
.SH SYNOPSIS
\fBhfs\fP [options] [\fIfile1\fP [\fIfile2\fP ...]]

.SH DESCRIPTION
http-file-share(\fIHFS\fP) is a file server that shares your files
across the HTTP protocol. After starting HFS, remote users
can open up a browser, connect to it, and download the desired files.
When a directory is shared, all its contents except symbolic link to
directories will be visible to remote users. If \fB--follow-link\fP is
given, contents of symbolic links to directories will also be listed.
To make downloading multiple files more convenient, the \fB--enable-tar\fP
option enables remote users to select multiple files to be packed and
downloaded as tar archives. You can limit the maximum download rate of
a single file by \fB--rate-limit\fP \fIlimit\fP.
.PP
HFS also support uploading files, yet this functionality is not so complete
currently. To enable uploading, set the directory to receive files by
\fB--upload-path\fP \fIdir\fP. The uploading function is tested to be working
on Firefox and Chrome/Chromium clients but currently fails on Microsoft
Internet Explorer. You can limit the maximum upload rate by
\fB--upload-rate-limit\fP \fIrate\fP.
.TP
\fB-h\fP, \fB--help\fP
show this help message and exit
.TP
\fB-p\fP \fIport\fP, \fB--port\fP \fIport\fP
set the port to listen on (needs root privilege to listen on port < 1024)
.TP
\fB-f\fP, \fB--follow-link\fP
follow symbolic links when listing files (disabled by default)
.TP
\fB--enable-tar\fP
enable remote user to download mutiple files altogether in a tar archive
(disabled by default)
.TP
\fB--rate-limit\fP \fIrate\fP
single file download (send to client) rate limit in kbyte/sec
.TP
\fB--upload-path\fP \fIdir\fP
save the received files in \fIdir\fP
.TP
\fB--upload-rate-limit\fP \fIrate\fP
single file upload (receive from client) rate limit in kbyte/sec
.TP
\fB--debug\fP
print debug message to stderr

.SH BUGS
The upload interface currently don't work on Microsoft Internet Explorer
clients.

.SH AUTHOR
Timothy Lin <lzh9102@gmail.com>
